### ISSUE TITLE
Use on Android htun

### ISSUE THREAD

**Issue by ingnelson** [AdrianVollmer/htun#3]
Hi.
This looks great ! .
Can be possible to use this on Android as client and the server on a VPS to create a tunnel and use it like VPN ?
Can someone can create a app that allow http headers request, please ?
This way we can use it bypass firewall from ISP and many people can use this excellent program .

I hope your answers.

**Comment by AdrianVollmer** [comment]
Hey there! Sorry, I didn't see this because somehow notifications were turned off and I didn't realize.

I have no plans porting this to Android and it would not be straight forward. I suggest you look into OpenVPN. It uses TLS and even supports HTTP proxies.
